# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "3.3.7";
      "sbtVersion" = "1.10.7";
    }];
  "repos" = {
    "nix-public" = "";
  };

  "artifacts" = {
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.pom";
      sha256 = "3E0C5721FB26BE732CCDF13DB1C59DFEEE0A6DB269EBCC7507EAD1C763A6108B";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.14.3/jackson-annotations-2.14.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.14.3/jackson-annotations-2.14.3-sources.jar";
      sha256 = "E6F7F659BB4ABD9BE1FE2F259F95A2340744AFF373EB34C134D6E2210BDC300D";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.14.3/jackson-annotations-2.14.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.14.3/jackson-annotations-2.14.3.jar";
      sha256 = "EA1B3A9EC60A353F4D7E78559C7140ABB9BCF71B31456E9D57C8289F7CF397F1";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.14.3/jackson-annotations-2.14.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.14.3/jackson-annotations-2.14.3.pom";
      sha256 = "0DBD47BBF3BFF518DB60BC5333C5D0E4439CF5F07D1D8A439AE0E0DEDE8EC85D";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.15.1/jackson-annotations-2.15.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.15.1/jackson-annotations-2.15.1-sources.jar";
      sha256 = "1AE0A927DF76A331CA0409595A8A84C8E3369F5696E5BC5D5DA06D26A1653DEA";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.15.1/jackson-annotations-2.15.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.15.1/jackson-annotations-2.15.1.jar";
      sha256 = "344C1B343D9819D5DD4395F2507977B91BB2463778CF2EF7B0D01724EC8FFAB2";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.15.1/jackson-annotations-2.15.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.15.1/jackson-annotations-2.15.1.pom";
      sha256 = "0CACB5A8537C72D78E41259D6D7E4F09FFE0F7AF9E86C588536D7F58E837E2E7";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1.pom";
      sha256 = "4D09B42B2ADCFE5CA73F541E42D1E36A8BF483594DF09C43BA8D31EB67E04626";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.14.3/jackson-core-2.14.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.14.3/jackson-core-2.14.3-sources.jar";
      sha256 = "3EE18051FF11CA9E0FD203BB163F2322C09573C76B6C1B13E2BD1031FB6F962A";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.14.3/jackson-core-2.14.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.14.3/jackson-core-2.14.3.jar";
      sha256 = "7EE2DEBAD3C002E97B28B84D5F1B2044A38E780ABB673948238F5BC656E2FE44";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.14.3/jackson-core-2.14.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.14.3/jackson-core-2.14.3.pom";
      sha256 = "2E5668CCE9F07CAE116522E91ECA12A87825F07A771C407AA0A915DC4A9200D0";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.15.1/jackson-core-2.15.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.15.1/jackson-core-2.15.1-sources.jar";
      sha256 = "8F2D5561CFE1C2C8DE09BC51ACB3B3E31EC884D89273AD30C5CEE30935946C23";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.15.1/jackson-core-2.15.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.15.1/jackson-core-2.15.1.jar";
      sha256 = "9D984319CC976E85C49F40DA928021ACD2D773E259A9FF9F832EDCDAC6920EED";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.15.1/jackson-core-2.15.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.15.1/jackson-core-2.15.1.pom";
      sha256 = "7C72AA68AEBDF50CF51010364D85896BA8188D15FBF4EE796F8A0614D613B686";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1.pom";
      sha256 = "98926399D5072408C20CD63063FBE29CF0923FC5061A3A56D6987F4DFF6FA223";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.14.3/jackson-databind-2.14.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.14.3/jackson-databind-2.14.3-sources.jar";
      sha256 = "F9F6C8DD8B543C02EEFC5844D068D90FF070AB913115BE5DF704B99B1988264B";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.14.3/jackson-databind-2.14.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.14.3/jackson-databind-2.14.3.jar";
      sha256 = "EF0694046DC86E8A601E69EFEF24CDA88A85773AAF012F5B9B1167D6F2E7DE45";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.14.3/jackson-databind-2.14.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.14.3/jackson-databind-2.14.3.pom";
      sha256 = "676D37EF88CF9B8C01A3830DC1115DE5AC1FEE4E02A715E8E7D52EA37B12DAA1";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.15.1/jackson-databind-2.15.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.15.1/jackson-databind-2.15.1-sources.jar";
      sha256 = "BB5231EF09A8C15F5C97327992CD47832CF3C7EE1F7AD83D4334144F9CFA8150";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.15.1/jackson-databind-2.15.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.15.1/jackson-databind-2.15.1.jar";
      sha256 = "C1F0347CE2696C94F531D095CD9EF22E648EC090E9B1C3DEE17938B07A1DF176";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.15.1/jackson-databind-2.15.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.15.1/jackson-databind-2.15.1.pom";
      sha256 = "EDC9AF251CB54283C2CB4159DDB33809927F0C8912ED421E2902C2D3AE062184";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.15.1/jackson-dataformat-yaml-2.15.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.15.1/jackson-dataformat-yaml-2.15.1-sources.jar";
      sha256 = "D782C643D9B3E02AD4287C2D42C6DED4ACC8CEA3FBDEF209C9F3B6EE72014898";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.15.1/jackson-dataformat-yaml-2.15.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.15.1/jackson-dataformat-yaml-2.15.1.jar";
      sha256 = "897F1B3509ADE0E70F1498B83CE410C8428B913B12AE4A7C1A6B0B22438BB182";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.15.1/jackson-dataformat-yaml-2.15.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.15.1/jackson-dataformat-yaml-2.15.1.pom";
      sha256 = "AA080187D1427E453F277603F90AA52E125CFB863954E4676CA3C3DCDDE78235";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformats-text/2.15.1/jackson-dataformats-text-2.15.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformats-text/2.15.1/jackson-dataformats-text-2.15.1.pom";
      sha256 = "C4B0A8A67A1C6372207899617796D869F13F51EAEB1AC37FC07A9CA713DA4235";
    };
    "nix-public/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1-sources.jar";
      sha256 = "B99AE335E94822194AB14DE4DBEE6D6FA75393A1C6788B13A3EAB167E40177A9";
    };
    "nix-public/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1.jar";
      sha256 = "B1B34405C980766CCE6C283FDC5039A274EA3B911F097B6807C21E1213B10292";
    };
    "nix-public/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.12.1/jackson-datatype-jsr310-2.12.1.pom";
      sha256 = "F44E4DA4876BB633CEBDB48D15F3D7D6D4F8B3D7DC5AFDBCD4343142B6C5C631";
    };
    "nix-public/com/fasterxml/jackson/jackson-base/2.12.1/jackson-base-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-base/2.12.1/jackson-base-2.12.1.pom";
      sha256 = "93A8C78755A31977508021DBB3883C0DD740A06BB1C67FF4942E096C132419F5";
    };
    "nix-public/com/fasterxml/jackson/jackson-base/2.14.3/jackson-base-2.14.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-base/2.14.3/jackson-base-2.14.3.pom";
      sha256 = "B42677A1A69094D78681D901CBFBD6C3B0972308C0FA3C63E1A3EC5890A1D569";
    };
    "nix-public/com/fasterxml/jackson/jackson-base/2.15.1/jackson-base-2.15.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-base/2.15.1/jackson-base-2.15.1.pom";
      sha256 = "A9D73D7BECBF421174568C382AB1629361180FA96FC041C2CD4A245F6963B09D";
    };
    "nix-public/com/fasterxml/jackson/jackson-bom/2.12.1/jackson-bom-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.12.1/jackson-bom-2.12.1.pom";
      sha256 = "083B20A4231BB0516D6E1A08248C9FBCE473583A122A07FD2E0EADEFF6908A38";
    };
    "nix-public/com/fasterxml/jackson/jackson-bom/2.14.3/jackson-bom-2.14.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.14.3/jackson-bom-2.14.3.pom";
      sha256 = "E845063C4D0C57B43AE04F3E640F85BD8A276BB47C42F2030B78262D6785F252";
    };
    "nix-public/com/fasterxml/jackson/jackson-bom/2.15.1/jackson-bom-2.15.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.15.1/jackson-bom-2.15.1.pom";
      sha256 = "C51747D114A597949F81140727D9E6CD63E3F43908F3647EFAA70B19E94DAA4D";
    };
    "nix-public/com/fasterxml/jackson/jackson-parent/2.12/jackson-parent-2.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.12/jackson-parent-2.12.pom";
      sha256 = "62AA1C1679ADE09F173DBF1B6C32D35C55E75800238FD5E48F13AA4337C0875B";
    };
    "nix-public/com/fasterxml/jackson/jackson-parent/2.14/jackson-parent-2.14.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.14/jackson-parent-2.14.pom";
      sha256 = "0906ADD855AE39F92357D63F485889B08FCA4C43A5FE433522D75344E0757B19";
    };
    "nix-public/com/fasterxml/jackson/jackson-parent/2.15/jackson-parent-2.15.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.15/jackson-parent-2.15.pom";
      sha256 = "6CDF97BC66F389F63E36850D2F552D1216688F8E5A58727D3F6A98EDF8675CDE";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-modules-java8/2.12.1/jackson-modules-java8-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-modules-java8/2.12.1/jackson-modules-java8-2.12.1.pom";
      sha256 = "C67B1D8ADBD06EFCDAC8EEF9EF569787F236E3869B81F86FFFF205EE1B4CB467";
    };
    "nix-public/com/fasterxml/oss-parent/41/oss-parent-41.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/oss-parent/41/oss-parent-41.pom";
      sha256 = "AF650FA4DD400BC5769320BCEF08ED93813F349CABE8213D469ACAFBBD945D8A";
    };
    "nix-public/com/fasterxml/oss-parent/48/oss-parent-48.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/oss-parent/48/oss-parent-48.pom";
      sha256 = "11BBA22D8631816E09B623A200747453D6491A66EAC8F5C089C73DA2B749014F";
    };
    "nix-public/com/fasterxml/oss-parent/50/oss-parent-50.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/oss-parent/50/oss-parent-50.pom";
      sha256 = "F5DA55DD7B88FB170C46801D17774A652FB2F4581FB5B1D0A5FC86AA182B8577";
    };
    "nix-public/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.6-3/zstd-jni-1.5.6-3.pom";
      sha256 = "DFD2FA7B1D23939216902F844FA5E86A79CDFB9209760E4C04242B5A58D49490";
    };
    "nix-public/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar";
      sha256 = "766AD2A0783F2687962C8AD74CEECC38A28B9F72A2D085EE438B7813E928D0C7";
    };
    "nix-public/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.pom";
      sha256 = "19889DBDF1B254B2601A5EE645B8147A974644882297684C798AFE5D63D78DFE";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2-sources.jar";
      sha256 = "F415EE5EB1B098FF3A132A918266277B3E859D150EB7216C418B0959069849F1";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2.jar";
      sha256 = "996F33EF589D0AA851E8BC3E0E2A0FAFF1B0447C35A9CD02AC9BEC4C400D7A94";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2.pom";
      sha256 = "634797F91CCE886BD226292A875A0BF5340F7AECD5752078253FFEEEBC63B06E";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2-sources.jar";
      sha256 = "51F4E031A2FE6D9B49F53F2739615EB10FBBA1D8970DF050B6EEFE42CB72EDBB";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2.jar";
      sha256 = "527D4A294778D7DCC7F309D407EBA0526816CED2D691C51308606B286ABF6573";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2.pom";
      sha256 = "873DEB3513093C7620C90A2271E3EF9E65EB843719E580AE1AE57DDDDB51E888";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2-sources.jar";
      sha256 = "1D7F1838A05837DCB7A2B30A39DC32B3E044EC2C728D6351D4AF839CEC4B3967";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2.jar";
      sha256 = "DCDEFC2DA8EC742AB81605276EBF300962613499C1196FB87E082BD76BC61789";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2.pom";
      sha256 = "B29AA651151E5CC505C89D6BB6F0BE4B830823FE93B4E8F42037BD155C0419D9";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2-sources.jar";
      sha256 = "47D40C2254A29DF4F324AE688A8CE7E7A23B370E10B1EB3592C207A91F0653CB";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2.jar";
      sha256 = "A46A7C2ABD5E8F2D6655B7E870408053E0BEB2DD14A5ACEC4F2B18F6E5B1F0CF";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2.pom";
      sha256 = "DEF45689E679E7D82AAD3DF7C2DDEEE8B106D58D9499304EC54A2FE823040B06";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2-sources.jar";
      sha256 = "D7C7F3773CD5636A0A67A3804A75642F0911A83211E51A2D3E73555CE340EFE6";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2.jar";
      sha256 = "B97CB3DF6DBD38A32BC1F90A7C81F5B112D8A390984E7A5F9FFF7D83F6E2D2C9";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2.pom";
      sha256 = "1ACA887B843D6516A70FAB3A66AF5200A5F35E09CEB98F2CA97BA935DAD01F1C";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2-sources.jar";
      sha256 = "65159ECF4262D7A4569D9F36BE4A5E8A65F1E3A6A17CF181D4467444E3CECC7C";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2.jar";
      sha256 = "15D217EF8F4D7702DA4C7C11A9FD192EEC3D67E9AB5486344DF95584E73336FA";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2.pom";
      sha256 = "5C23C3CB446C70C9F87C63BF65ADC2FE8655B329FB5C088F1828FA285D6E6CC0";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2-sources.jar";
      sha256 = "B0C537D203BC5F6D28A476125588DBC44121C6FE3A34458C3F405709A2B74E7F";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2.jar";
      sha256 = "C60FE12C39D48F548EF27BA55221483D76D4FBFC1476F4903414AD5AACD2395F";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2.pom";
      sha256 = "33AD16801947809B4947DE78BEB688CDE1BBACC76E2F170EEB34AEDC705F782B";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2-sources.jar";
      sha256 = "1101DFE8752E9419B586748B55934D97F18A91A9DB261C2BE03503B208836A02";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2.jar";
      sha256 = "761943D94020B78AC27C89840D9979328FC4CB18CB03AED23EE3B9767BF924B5";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2.pom";
      sha256 = "A081EB29B9BE8C254ADB567C69408E330460A69498A212CAB4275EDA57B15569";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2-sources.jar";
      sha256 = "0DBE35DDE394C3C6E982C51277404E6DC264D3A0BBE0377713F899EE06E8F8E5";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2.jar";
      sha256 = "370676119E0DB87453FE00D823C5B40172980CB24891EA4FEDACF88EFF909DA3";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2.pom";
      sha256 = "7C7922E67D47EDE8BF44D7DC5F7043488686BDA70F1F29471027FA2B5AE3D3C5";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2-sources.jar";
      sha256 = "C8EC44D1BF5D054DCA50F3531E90091E387D59B4C4EF3D79CA0A04EDD0DBFA39";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2.jar";
      sha256 = "D59096960D6C80B29B64D4D9DAC936B2C121D0B11C3E00B3DFCC1329DBC113B1";
    };
    "nix-public/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2.pom";
      sha256 = "EB1B60DFABE860E710D0AEA958EB95D03518B444EB392DA11B4116C830328BEA";
    };
    "nix-public/com/vladsch/flexmark/flexmark-java/0.62.2/flexmark-java-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-java/0.62.2/flexmark-java-0.62.2.pom";
      sha256 = "248DB1C4F979FDA7BF21E4A6221428536A191A38128DB4AD8DC6D088DA4F5C22";
    };
    "nix-public/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2-sources.jar";
      sha256 = "9549329D989E14DCB5F7DF7209DE14B03DEC0CE5E80D8F42D4173B15D374AA56";
    };
    "nix-public/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2.jar";
      sha256 = "E464FB813D747712E88784ED7459F9E1B1300FB53F8E5DCFEE90220811271512";
    };
    "nix-public/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2.pom";
      sha256 = "C7BA32E9B627BC8B9B38AB35122E449ECDC2360985121BF5B1972FAE21F2528B";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2-sources.jar";
      sha256 = "913C5C558176AE83C15CB0E3AD161BC8870F1A751FC823D275E7B4D8EE48F80E";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2.jar";
      sha256 = "762C1C2B9CEC0CDF53FE1FA1068061265A44F7BC33E672C13F838A697189E434";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2.pom";
      sha256 = "CED8C424A618821EA4FEAC0235BA7E2F9F45EF8C2EA14E27320E912BAD4838BA";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2-sources.jar";
      sha256 = "353D15015DCBE11CD78A80634F5E74CC4ACE613196031BF1AE0233AE51A067B6";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2.jar";
      sha256 = "1F3177ABF51B4E26E2BBA994DF4902B392C7336E16DFEE7AB2C492E0685D52F5";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2.pom";
      sha256 = "3A2C7261436990B00A801568D14D3EBD4F63F3D47714B4E4329D9CB2B2AEE863";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2-sources.jar";
      sha256 = "52A5F824BFC25186AE5766F8176EE99229A4A0B23AA90EEC8BBE6CC521C417AB";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2.jar";
      sha256 = "59F350F064AEB3D0E01E97FB773FB9701E3605D9DB7A6EB12BCE0686412B3809";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2.pom";
      sha256 = "212B6AF6047438702F91F3BEFD25370A5E7E617502737C383A3E0C29A64F4C97";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2-sources.jar";
      sha256 = "9DC0F68AACB067C61D36CD59BDE88A11B6D38D2D2DF774CB6C3A4513C5B6E90E";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2.jar";
      sha256 = "4EC42683F8AE51EE8227F3443A54EF0D70D076B593890ABAC24648D93EECC39C";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2.pom";
      sha256 = "38CB61557085B16B43BE1FCB88C5C5AB87475452B7F0915A6A2DF8626E242288";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2-sources.jar";
      sha256 = "402F9AD484F7C883944ECE9D98600493A148D7189E37298CA3E77FAD8A26B69B";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2.jar";
      sha256 = "582D01D2F3F42A9EA966551B354EDBD6C19DFC70BE74F470BC847DB255DE1367";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2.pom";
      sha256 = "D81F73FAB2BD41AB40D5279CC652BB0CB6C4F2CFE626241B6F416603A06CCFD6";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2-sources.jar";
      sha256 = "6F518303C29487CEF3FAB94F79D41C67705D50795CA0C4F61DAF44F09DB33F75";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2.jar";
      sha256 = "78CED2E678E746A78948CE9469FE95EC78C22D085B0254CCE7F826B40231087F";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2.pom";
      sha256 = "F1830E94348E34478E7CF759DBD1B404F815D74DF406707AEEBD130C1AB7FA49";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2-sources.jar";
      sha256 = "29C813F743A8DACB47308207857F51D308D3204ECF7984E396B0A51C1CA8D079";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2.jar";
      sha256 = "377BBF407BC7D7B091ADA9EBA16B058B7E7FA60ED4A3EE3C584C5D514E159786";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2.pom";
      sha256 = "370551FB04D87FCA7837D4C4EB49A373A80F1B1D0E799FE54821C42B2FCAA726";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2-sources.jar";
      sha256 = "D8B98BA7A212CBC5C419DFDA8030B40C5F242F17C85383347FE8FA756BFCCB6B";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2.jar";
      sha256 = "06CEC0698633F875E668B401DBAB208E0F56A5D55F956A993209EFAE6BE45DA6";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2.pom";
      sha256 = "BDE413317F2F2805F40D65E8B17270AEA9C0E87A1B8F4CF56C156256517CC67C";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2-sources.jar";
      sha256 = "7B6310D6A06F3AC972D7AE264A481CA64CFD16EB7D47C437B45D8736E5DB1DC1";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2.jar";
      sha256 = "A26573C1FEDB494D2FF06D28DB852D316F4D6FC3B43ED2247AFBACD743D9AE50";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2.pom";
      sha256 = "169AC9728A9473567DDA3539628C39D6D55B584B632E8A30B2A735BF1A5F88F9";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2-sources.jar";
      sha256 = "0056F66C4D65FEBC3AB820DBDFF9A002156A31FA0F8B3828F6E486051D257D46";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2.jar";
      sha256 = "6684A0048AD088452419A2871A6516E7FD3013700CB34A71CCA4F9F31A0320C4";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2.pom";
      sha256 = "4371C3C9E92D4625CAB53BD5D94A1DF4E390B54DE1FE561012C6824B0B834938";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2-sources.jar";
      sha256 = "C8FCFC0611720519368C29B84B156044A86A689D05E747E2D03F719CA43E876B";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2.jar";
      sha256 = "7197BFCFDECA859C2DA2D775F322F98B9FD722CB992760A9678BA4C706EAC982";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2.pom";
      sha256 = "F1AB51866153FE9EA09BE61CCB6DC22B2CE8B04FE3639A9194F0441FE2B9A3C4";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util/0.62.2/flexmark-util-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util/0.62.2/flexmark-util-0.62.2.jar";
      sha256 = "36BB72A3B57A99FF751190CB538AD553499BD49BC24763C642D58C61E9D5B171";
    };
    "nix-public/com/vladsch/flexmark/flexmark-util/0.62.2/flexmark-util-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark-util/0.62.2/flexmark-util-0.62.2.pom";
      sha256 = "83672CA119525DF59899400BDE45D19964B05AA34BE976697B64FD48DB6A3D1A";
    };
    "nix-public/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2-sources.jar";
      sha256 = "C22F2C40E16476B822F83B2A966B79C8AF490605822E64FDC884BC9FB9D1DADD";
    };
    "nix-public/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2.jar";
      sha256 = "5EBC1707B86C22C70A0EF7C5B7B38A9361C80B89B6BFD0E17BE39AB0ED3272A6";
    };
    "nix-public/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2.pom";
      sha256 = "38E4E8246F49623F6788AB188D2500FEDABCC235D411ED3F25D94DE18BF9CEC8";
    };
    "nix-public/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0-sources.jar";
      sha256 = "9869277D653510F670039B77945BEFE71C1CA34EF2E281855BD86E6605AAB4A6";
    };
    "nix-public/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0-tests.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0-tests.jar";
      sha256 = "949297112C37C82D3E3C0A54B28F0212DF35819D48AD042299253D924884FCF2";
    };
    "nix-public/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0.jar";
      sha256 = "F700DE80AC270D0344FDEA7468201D8B9C805E5C648331C3619F2EE067CCFC59";
    };
    "nix-public/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0.pom" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.17.0/commons-codec-1.17.0.pom";
      sha256 = "C01C4CDA5E408F41ED1D83E4A0A170CF53801B6338ABA49F0F904786BC1214FC";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1-sources.jar";
      sha256 = "FCFE84E39FB44E38A0EA0AB0815B53ADEA6FFF89C7B72535BC42495F400CB9A1";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1-tests.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1-tests.jar";
      sha256 = "12B99F1989D29DBBC3638FF9EEE855963F6B04262D4150C0FE49981FDBB37E14";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1.jar";
      sha256 = "F41F7BAACD716896447ACE9758621F62C1C6B0A91D89ACEE488DA26FC477C84F";
    };
    "nix-public/commons-io/commons-io/2.16.1/commons-io-2.16.1.pom" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.16.1/commons-io-2.16.1.pom";
      sha256 = "5777D292251C7895C04A4C57015683EC3B353A12486C9B3E7178E9B0B3C38FFF";
    };
    "nix-public/nl/big-o/liqp/0.8.2/liqp-0.8.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/nl/big-o/liqp/0.8.2/liqp-0.8.2-sources.jar";
      sha256 = "C3D1225F1ED152B979E9D43C76B8421ABBC7FBC424D1B57286C3040E8EDE59AC";
    };
    "nix-public/nl/big-o/liqp/0.8.2/liqp-0.8.2.jar" = {
      url = "https://repo1.maven.org/maven2/nl/big-o/liqp/0.8.2/liqp-0.8.2.jar";
      sha256 = "A948C26558E31FB445B5F1A2561C4518136A5D74046E4AB12BFB6010F6B0CC5B";
    };
    "nix-public/nl/big-o/liqp/0.8.2/liqp-0.8.2.pom" = {
      url = "https://repo1.maven.org/maven2/nl/big-o/liqp/0.8.2/liqp-0.8.2.pom";
      sha256 = "846DA39098C20BE8631523C62928E4DD2B4CF7686D428678AAE50060EEF009B8";
    };
    "nix-public/org/antlr/antlr4-master/4.7.2/antlr4-master-4.7.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/antlr/antlr4-master/4.7.2/antlr4-master-4.7.2.pom";
      sha256 = "BA99CB25D2390F38680C7502842A0EE0959D1E6403E013CCFF698FD5856EEAD1";
    };
    "nix-public/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2-sources.jar";
      sha256 = "6290B44CC5ABAAE2D747C966704E80CDFD742B4E2E0C8F9597F84A550E0D7F47";
    };
    "nix-public/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.jar";
      sha256 = "4C518B87D4BDFF8B44CD8CBC1AF816E944B62A3FE5B80B781501CF1F4759BBC4";
    };
    "nix-public/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.pom";
      sha256 = "DC09CBA98C25D3C06E4AEC516885D4C3AF03062BA55F4FE6283FC9CF176A60FB";
    };
    "nix-public/org/apache/apache/29/apache-29.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/29/apache-29.pom";
      sha256 = "3E49037174820BBD0DF63420A977255886398954C2A06291FA61F727AC35B377";
    };
    "nix-public/org/apache/apache/30/apache-30.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/30/apache-30.pom";
      sha256 = "63DD4A393A9C0DFCB314EFE83871A41D243BC8D200CBC7F2D197F30DA78239D8";
    };
    "nix-public/org/apache/apache/31/apache-31.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/31/apache-31.pom";
      sha256 = "555D0C9EAA69C042AFF924927B9381E8F8174136D355EEAD445224452E6291CC";
    };
    "nix-public/org/apache/avro/avro-parent/1.11.5/avro-parent-1.11.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/avro/avro-parent/1.11.5/avro-parent-1.11.5.pom";
      sha256 = "1F65A374F321B543A04B742CF6EEEB5C19D274DD35EFAC352896D144F8A202A3";
    };
    "nix-public/org/apache/avro/avro-toplevel/1.11.5/avro-toplevel-1.11.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/avro/avro-toplevel/1.11.5/avro-toplevel-1.11.5.pom";
      sha256 = "5A48A88AC044458B27A5E886914C87B957F996DBE5CC8354E8FA38C42AB6AFAF";
    };
    "nix-public/org/apache/avro/avro/1.11.5/avro-1.11.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/avro/avro/1.11.5/avro-1.11.5-sources.jar";
      sha256 = "A6A35C46961395CAE7E25D66100B33F1E53EF4DF3803FA9B16DDA7547B4FCA0F";
    };
    "nix-public/org/apache/avro/avro/1.11.5/avro-1.11.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/avro/avro/1.11.5/avro-1.11.5.jar";
      sha256 = "B3C55DA4C58304F823F4A2161A308888B9E7B8BC1C7387A4FA3CA1CD48617F93";
    };
    "nix-public/org/apache/avro/avro/1.11.5/avro-1.11.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/avro/avro/1.11.5/avro-1.11.5.pom";
      sha256 = "3F82F1CD542C1182EFC070AB6EE52F13A4219EF07D6369F368D1AF325940732F";
    };
    "nix-public/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2-sources.jar";
      sha256 = "89F2AC13872E1AC0024DC77573A0DA8E8E0DA2DDA58973F19244F6E60F08D138";
    };
    "nix-public/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2-tests.jar";
      sha256 = "5E59D46D2089641EA392C7AC059D38619AA664869FF5D2C1CAA26EAC512DD8DC";
    };
    "nix-public/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2.jar";
      sha256 = "9168A03141D8FC7EDA21A2360D83CC0412BCBB1D6204D992BD48C2573CB3C6B8";
    };
    "nix-public/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.26.2/commons-compress-1.26.2.pom";
      sha256 = "1428719895CD0A913AEE33E2424B9A804B10F1197E5D35A9CE99CF2A1174CB0E";
    };
    "nix-public/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0-sources.jar";
      sha256 = "AB3B86AFB898F1026DBE43AAF71E9C1D719EC52D6E41887B362D86777C299B6F";
    };
    "nix-public/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0-tests.jar";
      sha256 = "36BFD79260225E8EC173856A23E10FB6D514783EFCCCB1153804AA6C6CD2125E";
    };
    "nix-public/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar";
      sha256 = "7B96BF3EE68949ABB5BC465559AC270E0551596FA34523FDDF890EC418DDE13C";
    };
    "nix-public/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.pom";
      sha256 = "110438863BAD37C28F906BF87016E38C7A8C758BA321E09D11DC5A2363A8E79E";
    };
    "nix-public/org/apache/commons/commons-parent/64/commons-parent-64.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/64/commons-parent-64.pom";
      sha256 = "6F19638994E8357B4ED734696F992057EFAAFA1235673998133299798E2CCDDB";
    };
    "nix-public/org/apache/commons/commons-parent/69/commons-parent-69.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/69/commons-parent-69.pom";
      sha256 = "D50DA9C39BDCA823D618D1B4A03B73F196497FCB8616FD0DA727C8623592A9BB";
    };
    "nix-public/org/apache/commons/commons-text/1.11.0/commons-text-1.11.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-text/1.11.0/commons-text-1.11.0.jar";
      sha256 = "2ACF30A070B19163D5A480EAE411A281341E870020E3534C6D5D4C8472739E30";
    };
    "nix-public/org/apache/commons/commons-text/1.11.0/commons-text-1.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-text/1.11.0/commons-text-1.11.0.pom";
      sha256 = "3B401979C0641285D850CF118B4E18F049AC223DC785EAE4D0B35728FC534D11";
    };
    "nix-public/org/jetbrains/annotations/15.0/annotations-15.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jetbrains/annotations/15.0/annotations-15.0-sources.jar";
      sha256 = "5AB01A68DB908FA869038E1F30F3F6C31E6D90115142F24CED767F9BB7E845E0";
    };
    "nix-public/org/jetbrains/annotations/15.0/annotations-15.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jetbrains/annotations/15.0/annotations-15.0.jar";
      sha256 = "D74599CEF2B363FDB3CDD3198515ACA090E3EA3E98B2BA473C6E46F114DAB272";
    };
    "nix-public/org/jetbrains/annotations/15.0/annotations-15.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jetbrains/annotations/15.0/annotations-15.0.pom";
      sha256 = "6726678AC07B481B5E35D3AEEFCE526B95FD18EDE33D0D85CB1C688BCDF0E840";
    };
    "nix-public/org/jline/jline-native/3.29.0/jline-native-3.29.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-native/3.29.0/jline-native-3.29.0-sources.jar";
      sha256 = "6CDD8EDF54142ABC558916DF1372A93B115B823DF10FF5C05C11B988A66B2868";
    };
    "nix-public/org/jline/jline-native/3.29.0/jline-native-3.29.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-native/3.29.0/jline-native-3.29.0.jar";
      sha256 = "19CFCC9D3C78A1C6CFE4C6C9599F16A657E4BF8DA43940FC4B875373236DC258";
    };
    "nix-public/org/jline/jline-native/3.29.0/jline-native-3.29.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-native/3.29.0/jline-native-3.29.0.pom";
      sha256 = "5825548C79A919B6B1D8B7C0904BE72A1DE43E84AB5525923C2F91279F38DC83";
    };
    "nix-public/org/jline/jline-parent/3.29.0/jline-parent-3.29.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-parent/3.29.0/jline-parent-3.29.0.pom";
      sha256 = "7922EFD3D870A7D7AE03B196C300E35C5DE0228E59A5B012AEA641E36D79928E";
    };
    "nix-public/org/jline/jline-reader/3.29.0/jline-reader-3.29.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-reader/3.29.0/jline-reader-3.29.0-sources.jar";
      sha256 = "F22E92B22A17F16EC8427FDC42ED9C0CAAEFAADDAA35ED9BCC7A396D3E751B1D";
    };
    "nix-public/org/jline/jline-reader/3.29.0/jline-reader-3.29.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-reader/3.29.0/jline-reader-3.29.0.jar";
      sha256 = "A4CB0A5FDE9289F2F1B614E04F94B202F6FF5C9C96476425837B1184C92EF81D";
    };
    "nix-public/org/jline/jline-reader/3.29.0/jline-reader-3.29.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-reader/3.29.0/jline-reader-3.29.0.pom";
      sha256 = "D722F49A91292CFC69DA0E33A61B788DD4253E8174161639F640B21D461CC429";
    };
    "nix-public/org/jline/jline-terminal-jni/3.29.0/jline-terminal-jni-3.29.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jni/3.29.0/jline-terminal-jni-3.29.0-sources.jar";
      sha256 = "C0C0C46D1722873467FD6A0E45A664DFEF27156F4E62A300DBB4545F618B87B9";
    };
    "nix-public/org/jline/jline-terminal-jni/3.29.0/jline-terminal-jni-3.29.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jni/3.29.0/jline-terminal-jni-3.29.0.jar";
      sha256 = "13FEF8BCC0E4788C8E192DC76C33758683C6BFDBAEF6F67B41445EB8986773AD";
    };
    "nix-public/org/jline/jline-terminal-jni/3.29.0/jline-terminal-jni-3.29.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal-jni/3.29.0/jline-terminal-jni-3.29.0.pom";
      sha256 = "4DBEC22363D2FA1C4E2C89212F2626BC37F8D52D4DC43E8D87DF77AC64FFAFA4";
    };
    "nix-public/org/jline/jline-terminal/3.29.0/jline-terminal-3.29.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.29.0/jline-terminal-3.29.0-sources.jar";
      sha256 = "44899935C84500C3373DB4F8870C7A40D2DC69515264F8362531FC8C060CEA50";
    };
    "nix-public/org/jline/jline-terminal/3.29.0/jline-terminal-3.29.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.29.0/jline-terminal-3.29.0.jar";
      sha256 = "FD68A98B32B1132035C62102E5DF0B0FDC358E7C87A9F876CE7071450B4D10DA";
    };
    "nix-public/org/jline/jline-terminal/3.29.0/jline-terminal-3.29.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jline/jline-terminal/3.29.0/jline-terminal-3.29.0.pom";
      sha256 = "7BFA6055D005E2C8FE4A6EFC692AE6EFD7F543E3940FB55ECCA09D58C78CB0FE";
    };
    "nix-public/org/jsoup/jsoup/1.14.2/jsoup-1.14.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.2/jsoup-1.14.2.pom";
      sha256 = "DEF87047A7F3BA4817B256AC9361725865104DBE8AA5CC967068313B136D431A";
    };
    "nix-public/org/jsoup/jsoup/1.17.2/jsoup-1.17.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.17.2/jsoup-1.17.2-sources.jar";
      sha256 = "D108C67F7A3F0A352CB719D5D08105DA934A170A9B5AA576BC1B48C26961488A";
    };
    "nix-public/org/jsoup/jsoup/1.17.2/jsoup-1.17.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.17.2/jsoup-1.17.2.jar";
      sha256 = "F60B33B38E9D7AC93EAAA68A6C70F706BB99036494B2E2ADD2BFEE11D09AC6F5";
    };
    "nix-public/org/jsoup/jsoup/1.17.2/jsoup-1.17.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.17.2/jsoup-1.17.2.pom";
      sha256 = "7A349D217790C3730BE308CED1EA9EE32C4E74F72058E83C2B60E5A28954DD0D";
    };
    "nix-public/org/jspecify/jspecify/0.3.0/jspecify-0.3.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/jspecify/jspecify/0.3.0/jspecify-0.3.0.jar";
      sha256 = "E1C7E1832B6095FCFCBE57485700C7330D53D4E57E2C5BBF9C71819B02E978BE";
    };
    "nix-public/org/jspecify/jspecify/0.3.0/jspecify-0.3.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/jspecify/jspecify/0.3.0/jspecify-0.3.0.pom";
      sha256 = "F4B1B2AD61CA17F28D063C56109D3E839839A10B301BC97349543ECEEE57F316";
    };
    "nix-public/org/junit/junit-bom/5.10.0/junit-bom-5.10.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.10.0/junit-bom-5.10.0.pom";
      sha256 = "E006DD8894F9FC7B75FC32BB12FE5ED8BE65667D5B454F99E2E0B8C5BB8D30B3";
    };
    "nix-public/org/junit/junit-bom/5.10.2/junit-bom-5.10.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.10.2/junit-bom-5.10.2.pom";
      sha256 = "169DD904A4B0F6520CFFE658CC62292BFE9F3C14A989FA92120724CDE43A9968";
    };
    "nix-public/org/junit/junit-bom/5.9.2/junit-bom-5.9.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/junit/junit-bom/5.9.2/junit-bom-5.9.2.pom";
      sha256 = "2ED07D65845131F5336A86476C9A4056B59D0B58B9815AB3679BB0F36F35F705";
    };
    "nix-public/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0-sources.jar";
      sha256 = "26D6FBA888C9E332F6357773EF0500A7552C2453779A7D3E5D163E079546D8A8";
    };
    "nix-public/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0.jar";
      sha256 = "A80BE030F6386F18111CAD9161C0B6983157352A1B59A59E6002172F0D321C04";
    };
    "nix-public/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0.pom";
      sha256 = "916755647A34CCB367E11834D28380198C834ADFCF660E0D983E375B8F5C28F2";
    };
    "nix-public/org/osgi/org.osgi.core/6.0.0/org.osgi.core-6.0.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/osgi/org.osgi.core/6.0.0/org.osgi.core-6.0.0.jar";
      sha256 = "1C1BB435EB34CBF1F743653DA38F604D45D53FBC95979053768CD3FC293CB931";
    };
    "nix-public/org/osgi/org.osgi.core/6.0.0/org.osgi.core-6.0.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/osgi/org.osgi.core/6.0.0/org.osgi.core-6.0.0.pom";
      sha256 = "42A22743FB32DF6543536F78ADD4FCFD2557C8AF5D0BF0AFF5BA9D7491CDE350";
    };
    "nix-public/org/scala-lang/modules/scala-asm/9.8.0-scala-1/scala-asm-9.8.0-scala-1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.8.0-scala-1/scala-asm-9.8.0-scala-1-sources.jar";
      sha256 = "78543AB8BAFEC0E7D09227872DB06F4C725F5E0743F1F3EAB1F60EF6876588E9";
    };
    "nix-public/org/scala-lang/modules/scala-asm/9.8.0-scala-1/scala-asm-9.8.0-scala-1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.8.0-scala-1/scala-asm-9.8.0-scala-1.jar";
      sha256 = "86AF037580BDF9CE9C05F8B2AFD734DAF1A8564C38CD10CA5D08BF81508AD2E4";
    };
    "nix-public/org/scala-lang/modules/scala-asm/9.8.0-scala-1/scala-asm-9.8.0-scala-1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.8.0-scala-1/scala-asm-9.8.0-scala-1.pom";
      sha256 = "BF9866236DE05DA6F67BF15B94CF65832F9DBBB6B4A3A98BD963E75A234F8D90";
    };
    "nix-public/org/scala-lang/modules/scala-xml_3/2.1.0/scala-xml_3-2.1.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_3/2.1.0/scala-xml_3-2.1.0-sources.jar";
      sha256 = "B2F5F01C669F29DC03A8127F7A8CA2CDB40DFF3E29BA416E3DE4F6BEF0480ACA";
    };
    "nix-public/org/scala-lang/modules/scala-xml_3/2.1.0/scala-xml_3-2.1.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_3/2.1.0/scala-xml_3-2.1.0.jar";
      sha256 = "48F22343575F4B1D6550EECC42D4B7F0A0D30223C72F015D8D893FEAB4CBEECD";
    };
    "nix-public/org/scala-lang/modules/scala-xml_3/2.1.0/scala-xml_3-2.1.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_3/2.1.0/scala-xml_3-2.1.0.pom";
      sha256 = "D96029BE9FF2C847BDDE53A580E32CF769D9D6FBD3D025224BF66612B9EBE008";
    };
    "nix-public/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16-sources.jar";
      sha256 = "C02EDC324E7DB59C52115214A6EF36E2D78D0A50DFF635EDA4DCEE5502B1DEA5";
    };
    "nix-public/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.jar";
      sha256 = "1EBB2B6F9E4EB4022497C19B1E1E825019C08514F962AAAC197145F88ED730F1";
    };
    "nix-public/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.16/scala-library-2.13.16.pom";
      sha256 = "B25B72BA96EB30934868D86D307298D24D3AC154D362E7A4EEB37BA51BA86853";
    };
    "nix-public/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.pom";
      sha256 = "8021CD27867F1503C906E5A9881933309F2AD7DACA20CA13C96B81FBDC5EC9E8";
    };
    "nix-public/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.pom";
      sha256 = "4AE70B3CB0C215D69AEAC28C9212E6811F9EB978956782340608933420880D52";
    };
    "nix-public/org/scala-lang/scala3-compiler_3/3.3.7/scala3-compiler_3-3.3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.3.7/scala3-compiler_3-3.3.7-sources.jar";
      sha256 = "F0C43B55C79A02D013C37AB5B5BC0C74E7A92C6A237A400C7C025312075AD0BB";
    };
    "nix-public/org/scala-lang/scala3-compiler_3/3.3.7/scala3-compiler_3-3.3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.3.7/scala3-compiler_3-3.3.7.jar";
      sha256 = "E15FED89FB45248550C8227EA407C0EB496A6AFB7BDF7ABBA4285D2FE55BAF44";
    };
    "nix-public/org/scala-lang/scala3-compiler_3/3.3.7/scala3-compiler_3-3.3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.3.7/scala3-compiler_3-3.3.7.pom";
      sha256 = "812F147809FD8147349A33ADFDBB164A0C74A75EF0E9AEF97B0987AB5036990A";
    };
    "nix-public/org/scala-lang/scala3-interfaces/3.3.7/scala3-interfaces-3.3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.3.7/scala3-interfaces-3.3.7-sources.jar";
      sha256 = "E2376FDC50C23FD5784971B807060C04DBEA4807E5378A2C8C3DD82F8D29896D";
    };
    "nix-public/org/scala-lang/scala3-interfaces/3.3.7/scala3-interfaces-3.3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.3.7/scala3-interfaces-3.3.7.jar";
      sha256 = "F57F897043EFDA83576B5C18CE01DF5A5A1C2033EEB26224FC2A8D1FB779F82C";
    };
    "nix-public/org/scala-lang/scala3-interfaces/3.3.7/scala3-interfaces-3.3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.3.7/scala3-interfaces-3.3.7.pom";
      sha256 = "ABEAE521DE55BC164A1AD01B3EA284A5D9D969FBDAE3E4AE1B63C0430459AD59";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.0.2/scala3-library_3-3.0.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.0.2/scala3-library_3-3.0.2.pom";
      sha256 = "039E5BEE4D4ECB63C2BAC58BF249FA02EDF4568AFFD7363E93B201A340E7D5B5";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.1.3/scala3-library_3-3.1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.1.3/scala3-library_3-3.1.3.pom";
      sha256 = "D61E035994E678729D9EF1DCFE538BFE1E4A94E665DBD961A0FA327411A2F4D3";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7-sources.jar";
      sha256 = "D06C4573324F048C6E4F0526DA6B63753F20102BE1FC8C752C97E3BB6B0E80C2";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7.jar";
      sha256 = "A16E046F4A9DF9E0D0E0BC54BF6298C94D7D867457F7B3B68291A88C568B92D0";
    };
    "nix-public/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.3.7/scala3-library_3-3.3.7.pom";
      sha256 = "992BB5414F5855DA7884134EB518D5F700E2849E8F3C4D5164E5C4215EBA2151";
    };
    "nix-public/org/scala-lang/scala3-sbt-bridge/3.3.7/scala3-sbt-bridge-3.3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-sbt-bridge/3.3.7/scala3-sbt-bridge-3.3.7-sources.jar";
      sha256 = "C7811196F5CFDD6ABCF271E97000C3957BE8521CB9CFCB38599D9E628E3F5D52";
    };
    "nix-public/org/scala-lang/scala3-sbt-bridge/3.3.7/scala3-sbt-bridge-3.3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-sbt-bridge/3.3.7/scala3-sbt-bridge-3.3.7.jar";
      sha256 = "3847B6609F800E995D1D1D8F41D591B75EE7397668E0DF1C16DBA4C7C54AA9EB";
    };
    "nix-public/org/scala-lang/scala3-sbt-bridge/3.3.7/scala3-sbt-bridge-3.3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-sbt-bridge/3.3.7/scala3-sbt-bridge-3.3.7.pom";
      sha256 = "20FBE854BBAC8E8652D0B5BB5EEA66FAC8B431AB694E2BB244AFC6315EF07BF8";
    };
    "nix-public/org/scala-lang/scala3-tasty-inspector_3/3.3.7/scala3-tasty-inspector_3-3.3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-tasty-inspector_3/3.3.7/scala3-tasty-inspector_3-3.3.7-sources.jar";
      sha256 = "4BEDB504BCC5D921A93CEBFD71249FA049B1295E5842A263F0417C8FD83658C7";
    };
    "nix-public/org/scala-lang/scala3-tasty-inspector_3/3.3.7/scala3-tasty-inspector_3-3.3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-tasty-inspector_3/3.3.7/scala3-tasty-inspector_3-3.3.7.jar";
      sha256 = "C7594949816C580CCBFA1CB90DED93CF80A56A7E39EE1DE5F5F3AAACEEFDB5BA";
    };
    "nix-public/org/scala-lang/scala3-tasty-inspector_3/3.3.7/scala3-tasty-inspector_3-3.3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala3-tasty-inspector_3/3.3.7/scala3-tasty-inspector_3-3.3.7.pom";
      sha256 = "CF03D950328F51E526C07256826C18308CAD815A050FB75E5D2A5BA9176829E2";
    };
    "nix-public/org/scala-lang/scaladoc_3/3.3.7/scaladoc_3-3.3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scaladoc_3/3.3.7/scaladoc_3-3.3.7-sources.jar";
      sha256 = "0220EA68F7CA45F32A357EEA2252226B8D7CDEED69D102620460692DED163B97";
    };
    "nix-public/org/scala-lang/scaladoc_3/3.3.7/scaladoc_3-3.3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scaladoc_3/3.3.7/scaladoc_3-3.3.7.jar";
      sha256 = "8115F8ED937FCE7F7C22271C57846C2F35E6BCDAA410C41FD43D5FB4FB1E0DEF";
    };
    "nix-public/org/scala-lang/scaladoc_3/3.3.7/scaladoc_3-3.3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scaladoc_3/3.3.7/scaladoc_3-3.3.7.pom";
      sha256 = "507D488925419F0EB654790EC0DEFAE27F5C1DBC844DA2CA4A79BA6CFC11AE4D";
    };
    "nix-public/org/scala-lang/tasty-core_3/3.3.7/tasty-core_3-3.3.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.3.7/tasty-core_3-3.3.7-sources.jar";
      sha256 = "EE9ED10E4C0F3CFDE863FE5588BE5FDB276D71C7D48345A18A5940D9FBFCC5B6";
    };
    "nix-public/org/scala-lang/tasty-core_3/3.3.7/tasty-core_3-3.3.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.3.7/tasty-core_3-3.3.7.jar";
      sha256 = "0748CD71C48398888313CB3C00B8AAD39BD02F94D43CBCA657D52903517A1E5A";
    };
    "nix-public/org/scala-lang/tasty-core_3/3.3.7/tasty-core_3-3.3.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/tasty-core_3/3.3.7/tasty-core_3-3.3.7.pom";
      sha256 = "D67EE18BAA002E6DC12AEFB8B9F28D817D56BBA1BF683BA4EEA3475CBFB28FDA";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7-sources.jar";
      sha256 = "6BF753FBA3AFAD192B1837858A2E68D5969976375C27B8E2969CDEA952EFB47F";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7.jar";
      sha256 = "2BACC5761E03920A228E5C9D20B33D9C51D43AAF2F52E8F839ECE630966EB880";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.10.7/compiler-interface-1.10.7.pom";
      sha256 = "3B7B0DA8BF5820AA50F4448E19021DE1183164F74A180BD0B68E7D92F3004E31";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom";
      sha256 = "61BA06A9D0C226E10F048004FCEBFB300FDD9B077D05ED502E9875324C8B762E";
    };
    "nix-public/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7-sources.jar";
      sha256 = "6AC907710F3BB66A94E2A5D5703AEF5D16DDC1BBAF35185E9F6ACA1354956B12";
    };
    "nix-public/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7.jar";
      sha256 = "1D6B91EFA42B70FC064CAED6D62962374E13B27737F885A87C84C667B30BE625";
    };
    "nix-public/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.10.7/util-interface-1.10.7.pom";
      sha256 = "D49470C815E070E44F9501116C83F35B179413F5AAFE95E29AC293C67CC16297";
    };
    "nix-public/org/scalactic/scalactic_3/3.2.17/scalactic_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_3/3.2.17/scalactic_3-3.2.17-sources.jar";
      sha256 = "8700A6C7B532D1B8CAFF83AC61A612A6A2B9E817612909B47707E2D7D22E2FC3";
    };
    "nix-public/org/scalactic/scalactic_3/3.2.17/scalactic_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_3/3.2.17/scalactic_3-3.2.17.jar";
      sha256 = "9AA9CC85A354AA2118DF99F743FD46435451B31BDB2E974255705D198A4E9F84";
    };
    "nix-public/org/scalactic/scalactic_3/3.2.17/scalactic_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_3/3.2.17/scalactic_3-3.2.17.pom";
      sha256 = "97103FE40DF8E67BA06FCB46AA3D705A0259D7513BD729F3129D947A28F8E5F8";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.17/scalatest-compatible-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.17/scalatest-compatible-3.2.17-sources.jar";
      sha256 = "4473936E62A1E3F91B36B28E2BB2DDF8B2B2D0A6A5F7284B2817F1359D70EBEE";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.17/scalatest-compatible-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.17/scalatest-compatible-3.2.17.jar";
      sha256 = "7A1D8A37B5B453B6D93147D595C0B09043317650B6FFCDC89E3817B223F77E5F";
    };
    "nix-public/org/scalatest/scalatest-compatible/3.2.17/scalatest-compatible-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-compatible/3.2.17/scalatest-compatible-3.2.17.pom";
      sha256 = "F2CA4D5FFA6E6B2E2CB56C37B00D826A3B9CF7561C4130B8ADB831D566EA7481";
    };
    "nix-public/org/scalatest/scalatest-core_3/3.2.17/scalatest-core_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-core_3/3.2.17/scalatest-core_3-3.2.17-sources.jar";
      sha256 = "3FFA0A32CB6823D8B912CCA820007417AD2C2C2CFD711C1FBC47B26D0087EE70";
    };
    "nix-public/org/scalatest/scalatest-core_3/3.2.17/scalatest-core_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-core_3/3.2.17/scalatest-core_3-3.2.17.jar";
      sha256 = "9329D5414B9ACFA09522F763C0F40933583C4406C34A1A2EFE64509AE726E0EB";
    };
    "nix-public/org/scalatest/scalatest-core_3/3.2.17/scalatest-core_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-core_3/3.2.17/scalatest-core_3-3.2.17.pom";
      sha256 = "864E0AFEB075465AD89C177C298E32087C7EC22389D8C0F32B0EB52EAB69C961";
    };
    "nix-public/org/scalatest/scalatest-diagrams_3/3.2.17/scalatest-diagrams_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-diagrams_3/3.2.17/scalatest-diagrams_3-3.2.17-sources.jar";
      sha256 = "5CDB1C819C76890987368C782E47FB519AD290B63119E6CBF784E9AE7CC2CFF5";
    };
    "nix-public/org/scalatest/scalatest-diagrams_3/3.2.17/scalatest-diagrams_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-diagrams_3/3.2.17/scalatest-diagrams_3-3.2.17.jar";
      sha256 = "42CFFAEFE5A833ABECF70F901698EA1866F51CB83ABF075C48E0F4459A2C65DF";
    };
    "nix-public/org/scalatest/scalatest-diagrams_3/3.2.17/scalatest-diagrams_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-diagrams_3/3.2.17/scalatest-diagrams_3-3.2.17.pom";
      sha256 = "1F7291F32B0EBC951B2F730F4FDE550F08979E4BA1C7A776608557188EF1D45E";
    };
    "nix-public/org/scalatest/scalatest-featurespec_3/3.2.17/scalatest-featurespec_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-featurespec_3/3.2.17/scalatest-featurespec_3-3.2.17-sources.jar";
      sha256 = "23E1CF82EFC0A1BF43D5AB8F3D87125A81D689206A1034EB9C0DEC0A9FF67668";
    };
    "nix-public/org/scalatest/scalatest-featurespec_3/3.2.17/scalatest-featurespec_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-featurespec_3/3.2.17/scalatest-featurespec_3-3.2.17.jar";
      sha256 = "1C8EE5B0C1BD5A8C3093BF3DEEB6A0B07AF655B8A163A477590795F5C6FE6266";
    };
    "nix-public/org/scalatest/scalatest-featurespec_3/3.2.17/scalatest-featurespec_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-featurespec_3/3.2.17/scalatest-featurespec_3-3.2.17.pom";
      sha256 = "433CE2DD16BAAA3E00E2A715CF9364CB60C83DA9A2FFE021CFE4EEA9B78D8181";
    };
    "nix-public/org/scalatest/scalatest-flatspec_3/3.2.17/scalatest-flatspec_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-flatspec_3/3.2.17/scalatest-flatspec_3-3.2.17-sources.jar";
      sha256 = "3137DEB81CE4217E8BF2667CF139A3D9066C2DF5C20248588BFE769303F432AE";
    };
    "nix-public/org/scalatest/scalatest-flatspec_3/3.2.17/scalatest-flatspec_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-flatspec_3/3.2.17/scalatest-flatspec_3-3.2.17.jar";
      sha256 = "A695961C603F1AD32CA28BF3F925234D5D7348AB786E4959CADE4724F536C79B";
    };
    "nix-public/org/scalatest/scalatest-flatspec_3/3.2.17/scalatest-flatspec_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-flatspec_3/3.2.17/scalatest-flatspec_3-3.2.17.pom";
      sha256 = "DB00EA6FF160747C70643DAC12B18D436C4A4ED61B776764E386211455AFD98B";
    };
    "nix-public/org/scalatest/scalatest-freespec_3/3.2.17/scalatest-freespec_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-freespec_3/3.2.17/scalatest-freespec_3-3.2.17-sources.jar";
      sha256 = "A6BC77233946C109604B2AEB8543B2017DC69E3994D7CCF515A22E7A38062E2F";
    };
    "nix-public/org/scalatest/scalatest-freespec_3/3.2.17/scalatest-freespec_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-freespec_3/3.2.17/scalatest-freespec_3-3.2.17.jar";
      sha256 = "949C81806F5DBE8BB8C914F00596E5098BB403167D8978D3D2B32229B0826EE5";
    };
    "nix-public/org/scalatest/scalatest-freespec_3/3.2.17/scalatest-freespec_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-freespec_3/3.2.17/scalatest-freespec_3-3.2.17.pom";
      sha256 = "23470D62CCEB93C133B845B83EAEE434453418085E9D30FABCFA4877780793A0";
    };
    "nix-public/org/scalatest/scalatest-funspec_3/3.2.17/scalatest-funspec_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funspec_3/3.2.17/scalatest-funspec_3-3.2.17-sources.jar";
      sha256 = "C780302541AAEFC66F6A731476EA920B0F4CEAA5394D9DBB46F823868847BA65";
    };
    "nix-public/org/scalatest/scalatest-funspec_3/3.2.17/scalatest-funspec_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funspec_3/3.2.17/scalatest-funspec_3-3.2.17.jar";
      sha256 = "2D64DE7C3A04264C535C108DC74AF35205FA1E51C8386204D1B3A7BF129DAC00";
    };
    "nix-public/org/scalatest/scalatest-funspec_3/3.2.17/scalatest-funspec_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funspec_3/3.2.17/scalatest-funspec_3-3.2.17.pom";
      sha256 = "CA49C6D3DBDD26612D8910A794F7EED5FDBF73EF8549CAA118334A7C954594FE";
    };
    "nix-public/org/scalatest/scalatest-funsuite_3/3.2.17/scalatest-funsuite_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funsuite_3/3.2.17/scalatest-funsuite_3-3.2.17-sources.jar";
      sha256 = "E882DA2817822747435836283E23F8EE83F54E6E33CC280F1E89D79D22A54EE5";
    };
    "nix-public/org/scalatest/scalatest-funsuite_3/3.2.17/scalatest-funsuite_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funsuite_3/3.2.17/scalatest-funsuite_3-3.2.17.jar";
      sha256 = "4D82F5A7C7D61B381F9C0B694DA11121D4B30631B75893320942C687C60C48DA";
    };
    "nix-public/org/scalatest/scalatest-funsuite_3/3.2.17/scalatest-funsuite_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-funsuite_3/3.2.17/scalatest-funsuite_3-3.2.17.pom";
      sha256 = "043A5FE69B4E31B49EB157BA0B8F29CC1633CCAB538664B08BE06C8AB650EB1D";
    };
    "nix-public/org/scalatest/scalatest-matchers-core_3/3.2.17/scalatest-matchers-core_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-matchers-core_3/3.2.17/scalatest-matchers-core_3-3.2.17-sources.jar";
      sha256 = "D603C88B384E26AAA26F8F2EE0F700FE5A4F2199C9AF9E5EAE9E4D85ED747361";
    };
    "nix-public/org/scalatest/scalatest-matchers-core_3/3.2.17/scalatest-matchers-core_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-matchers-core_3/3.2.17/scalatest-matchers-core_3-3.2.17.jar";
      sha256 = "6EE67768760FCC3648C56DA140437EC57FED5C49DB23BE657FDF619EA98CBB45";
    };
    "nix-public/org/scalatest/scalatest-matchers-core_3/3.2.17/scalatest-matchers-core_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-matchers-core_3/3.2.17/scalatest-matchers-core_3-3.2.17.pom";
      sha256 = "D328B313CDCF633A3B6FCB0C18E3DA5F422DAC975D798338E05CEC9CDE8B1975";
    };
    "nix-public/org/scalatest/scalatest-mustmatchers_3/3.2.17/scalatest-mustmatchers_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-mustmatchers_3/3.2.17/scalatest-mustmatchers_3-3.2.17-sources.jar";
      sha256 = "9BB0C5C383334B7B43E1F372972DFE9A54053C0416081C20C21E9E8A335267A2";
    };
    "nix-public/org/scalatest/scalatest-mustmatchers_3/3.2.17/scalatest-mustmatchers_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-mustmatchers_3/3.2.17/scalatest-mustmatchers_3-3.2.17.jar";
      sha256 = "961AF5708CEB32B10B921D6B6029C0DB31A2BACB33A1D9A6A12535A31D6488A2";
    };
    "nix-public/org/scalatest/scalatest-mustmatchers_3/3.2.17/scalatest-mustmatchers_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-mustmatchers_3/3.2.17/scalatest-mustmatchers_3-3.2.17.pom";
      sha256 = "69AB7C84AA548FA772C12CABAC391C442479A309D0D3F184715008DB1D6CDBCB";
    };
    "nix-public/org/scalatest/scalatest-propspec_3/3.2.17/scalatest-propspec_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-propspec_3/3.2.17/scalatest-propspec_3-3.2.17-sources.jar";
      sha256 = "5C1865BCAD9BC980E0686221463F0322A2FB114D32E7B5A8FA2D71D031637BBF";
    };
    "nix-public/org/scalatest/scalatest-propspec_3/3.2.17/scalatest-propspec_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-propspec_3/3.2.17/scalatest-propspec_3-3.2.17.jar";
      sha256 = "78E73A51F624742FAFA68690F4FB7D2F645BB36254B7C4E9E242D5D65D8BC28D";
    };
    "nix-public/org/scalatest/scalatest-propspec_3/3.2.17/scalatest-propspec_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-propspec_3/3.2.17/scalatest-propspec_3-3.2.17.pom";
      sha256 = "F84BA8A3698830DD8FD8B2C0B3CBDA9B073FC48BC5B766970E531C8542B170F3";
    };
    "nix-public/org/scalatest/scalatest-refspec_3/3.2.17/scalatest-refspec_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-refspec_3/3.2.17/scalatest-refspec_3-3.2.17-sources.jar";
      sha256 = "E07B1858EC45581A7280DC99C372F5EDE2CE7A2142887C8D7EB3470B6DE9C759";
    };
    "nix-public/org/scalatest/scalatest-refspec_3/3.2.17/scalatest-refspec_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-refspec_3/3.2.17/scalatest-refspec_3-3.2.17.jar";
      sha256 = "F9B99952880AD524C9084A633887C366099BA05DF8036AB2F9FAA773B6A71F35";
    };
    "nix-public/org/scalatest/scalatest-refspec_3/3.2.17/scalatest-refspec_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-refspec_3/3.2.17/scalatest-refspec_3-3.2.17.pom";
      sha256 = "815E24C4760FB988BAAB39F94B9F5BC7CAFCFB5637D676FE4462FE06825A6C1C";
    };
    "nix-public/org/scalatest/scalatest-shouldmatchers_3/3.2.17/scalatest-shouldmatchers_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-shouldmatchers_3/3.2.17/scalatest-shouldmatchers_3-3.2.17-sources.jar";
      sha256 = "2F03C7C3410C5F40273B48C14614714EB015F88F2AD91E411E37381865CBA6ED";
    };
    "nix-public/org/scalatest/scalatest-shouldmatchers_3/3.2.17/scalatest-shouldmatchers_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-shouldmatchers_3/3.2.17/scalatest-shouldmatchers_3-3.2.17.jar";
      sha256 = "DE627BEA353BE078FEAEB392FA61F59F6AC5C52A644C6AD3A0032210A5669190";
    };
    "nix-public/org/scalatest/scalatest-shouldmatchers_3/3.2.17/scalatest-shouldmatchers_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-shouldmatchers_3/3.2.17/scalatest-shouldmatchers_3-3.2.17.pom";
      sha256 = "62496011823B5C89354513A2E60C01B3EB7FCC4F0093DDD518EF274CD242F563";
    };
    "nix-public/org/scalatest/scalatest-wordspec_3/3.2.17/scalatest-wordspec_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_3/3.2.17/scalatest-wordspec_3-3.2.17-sources.jar";
      sha256 = "8DCF1E15CED89EC44135D6CCB11140981429A5F4139123412EA116A53B2723D1";
    };
    "nix-public/org/scalatest/scalatest-wordspec_3/3.2.17/scalatest-wordspec_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_3/3.2.17/scalatest-wordspec_3-3.2.17.jar";
      sha256 = "B8824ABCC55CAAA17FE841C5708511BE52D29C4E2374F931D666CC513F769347";
    };
    "nix-public/org/scalatest/scalatest-wordspec_3/3.2.17/scalatest-wordspec_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest-wordspec_3/3.2.17/scalatest-wordspec_3-3.2.17.pom";
      sha256 = "034C7FEC7A0ECEA3BCA9E9AEAF4BE360632E746EF689B3DCAFFDB9480020BE9C";
    };
    "nix-public/org/scalatest/scalatest_3/3.2.17/scalatest_3-3.2.17-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_3/3.2.17/scalatest_3-3.2.17-sources.jar";
      sha256 = "A441E6EA5692141DD4DA4635D41B71BA9F210653603A56F13C8629E2446F37E3";
    };
    "nix-public/org/scalatest/scalatest_3/3.2.17/scalatest_3-3.2.17.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_3/3.2.17/scalatest_3-3.2.17.jar";
      sha256 = "24CD549C6746057776C22A5BA9D5501BC3C620337F3924B1851046335BAD0109";
    };
    "nix-public/org/scalatest/scalatest_3/3.2.17/scalatest_3-3.2.17.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_3/3.2.17/scalatest_3-3.2.17.pom";
      sha256 = "17A3F8024642353FFF5E7C72F6838510F776EE8A72C034D4979524AF3169F342";
    };
    "nix-public/org/slf4j/log4j-over-slf4j/2.0.18/log4j-over-slf4j-2.0.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/2.0.18/log4j-over-slf4j-2.0.18-sources.jar";
      sha256 = "E19E4DB770231FDFC4D65E864D92002AF72AEC86967155F3D01AEC6B38BDD557";
    };
    "nix-public/org/slf4j/log4j-over-slf4j/2.0.18/log4j-over-slf4j-2.0.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/2.0.18/log4j-over-slf4j-2.0.18.jar";
      sha256 = "D030643B4B3371AC79CE9A5BF2E4F82B65EE5621E2C0C6BBFB254D74C9A90DF6";
    };
    "nix-public/org/slf4j/log4j-over-slf4j/2.0.18/log4j-over-slf4j-2.0.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/log4j-over-slf4j/2.0.18/log4j-over-slf4j-2.0.18.pom";
      sha256 = "E0DF5BB3C227AFB840B0E79B1254079B275A235B9F5A74B3B5FC80919C9C79AE";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36-sources.jar";
      sha256 = "15BC04357A3725B7A5153F132DB71379F95E83B7B8590A86CC6D4AD77BFC150A";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36-tests.jar";
      sha256 = "EF8E69388790DE8D61DB8C6283A85A26AB4659BEA608B6AF576EE89F2AF91879";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar";
      sha256 = "D3EF575E3E4979678DC01BF1DCCE51021493B4D11FB7F1BE8AD982877C16A1C0";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.pom";
      sha256 = "FB046A9C229437928BB11C2D27C8B5D773EB8A25E60CBD253D985210DEDC2684";
    };
    "nix-public/org/slf4j/slf4j-api/2.0.18/slf4j-api-2.0.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.18/slf4j-api-2.0.18-sources.jar";
      sha256 = "192E007CF7F2BE41D40574E44521FC0B7CE55E01F13DBE0FA8707C8AE3329075";
    };
    "nix-public/org/slf4j/slf4j-api/2.0.18/slf4j-api-2.0.18-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.18/slf4j-api-2.0.18-tests.jar";
      sha256 = "3E060C3329EDA5B7CCC153EBC3B9FD47CC062E210775ADA34EA702A5948AC464";
    };
    "nix-public/org/slf4j/slf4j-api/2.0.18/slf4j-api-2.0.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.18/slf4j-api-2.0.18.jar";
      sha256 = "44508FD1576500688C790B190ACDD16FEC4F8C79A3E0B900AFD70503CF055F55";
    };
    "nix-public/org/slf4j/slf4j-api/2.0.18/slf4j-api-2.0.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.18/slf4j-api-2.0.18.pom";
      sha256 = "6C2C7F2C02774CC2B7B619FBD2DF7873CDAD29718926E44754B87F70D1EB43CB";
    };
    "nix-public/org/slf4j/slf4j-bom/2.0.18/slf4j-bom-2.0.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-bom/2.0.18/slf4j-bom-2.0.18.pom";
      sha256 = "9219AAB601575126C4E66E1331EB2B0C6C17A330AC4D5A07E3CD11D580A0C12D";
    };
    "nix-public/org/slf4j/slf4j-nop/2.0.18/slf4j-nop-2.0.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/2.0.18/slf4j-nop-2.0.18-sources.jar";
      sha256 = "4E58703F602FF6EEAD128FBA75364D67EEA70F4AC685F5F919D368E7D9B89B73";
    };
    "nix-public/org/slf4j/slf4j-nop/2.0.18/slf4j-nop-2.0.18.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/2.0.18/slf4j-nop-2.0.18.jar";
      sha256 = "40E6BE27D583D884183CA466CD20203112691F2A075A650E9E8D5C2E51AA5F49";
    };
    "nix-public/org/slf4j/slf4j-nop/2.0.18/slf4j-nop-2.0.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/2.0.18/slf4j-nop-2.0.18.pom";
      sha256 = "BBC4116E093DAC21BBA7ACC44E372D288BF2309B9BF0313F3C92D346CDE40E79";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.36/slf4j-parent-1.7.36.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.36/slf4j-parent-1.7.36.pom";
      sha256 = "BB388D37FBCDD3CDE64C3CEDE21838693218DC451F04040C5DF360A78ED7E812";
    };
    "nix-public/org/slf4j/slf4j-parent/2.0.18/slf4j-parent-2.0.18.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/2.0.18/slf4j-parent-2.0.18.pom";
      sha256 = "0B3896BEDAD2C9ED9697EDCBEA1DA0C54CD238A723583A81358A83BFB782E9FA";
    };
    "nix-public/org/sonatype/oss/oss-parent/7/oss-parent-7.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom";
      sha256 = "B51F8867C92B6A722499557FC3A1FDEA77BDF9EF574722FE90CE436A29559454";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom";
      sha256 = "FB40265F982548212FF82E362E59732B2187EC6F0D80182885C14EF1F982827A";
    };
    "nix-public/org/tukaani/xz/1.9/xz-1.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/tukaani/xz/1.9/xz-1.9.pom";
      sha256 = "093BE1B03331BCE2932D6825C37E98272D7621E6A9E9FB93289A002518B8DD5A";
    };
    "nix-public/org/yaml/snakeyaml/2.0/snakeyaml-2.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/yaml/snakeyaml/2.0/snakeyaml-2.0-sources.jar";
      sha256 = "9B336F77718EE80225D3D878FE5AB753E9863614FB84E3E859D51432DDE43199";
    };
    "nix-public/org/yaml/snakeyaml/2.0/snakeyaml-2.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/yaml/snakeyaml/2.0/snakeyaml-2.0.jar";
      sha256 = "880C9D896E4B74A06C549C15CA496450165D6909FA15D7E662BEE8F6A66D7AFA";
    };
    "nix-public/org/yaml/snakeyaml/2.0/snakeyaml-2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/yaml/snakeyaml/2.0/snakeyaml-2.0.pom";
      sha256 = "43C761F92B549C8B08FB992080253E49F0A983E544EF0663C1F4F9D68EB52616";
    };
    "nix-public/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5-sources.jar";
      sha256 = "33A2CC43EEE1C2C1C3A57E68783B5B93CA05041C1505E67799DA43B0595E966C";
    };
    "nix-public/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5.jar" = {
      url = "https://repo1.maven.org/maven2/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5.jar";
      sha256 = "8EE3BE181A1D3871D2B14E1E145CBC48918ABBBF3596268FDD4B3D7292B07FC9";
    };
    "nix-public/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5.pom" = {
      url = "https://repo1.maven.org/maven2/ua/co/k/strftime4j/1.0.5/strftime4j-1.0.5.pom";
      sha256 = "DF50D06823A4F87C3FD739EBD1718F09BC126BB8206DFDE8C477B3A816EDF500";
    };
  };
}