name: master

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '*.md'
      - '*.yml'
    branches:
      - master
      - release/5*

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Nix (with flake support)
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: sandbox = true

      - name: Use Cachix
        uses: cachix/cachix-action@v10
        with:
          name: avro4s
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          push: true

      - name: Run Tests
        run: nix develop --command sbt test

      - name: Build with Nix
        run: nix build

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}

      - name: Show GPG user IDs (Optional)
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"

      - name: Publish Snapshot
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: nix develop --command sbt publishSigned
