name: pr_scala_3

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - '*.md'
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repository
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Install Nix with flake support
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: sandbox = true

      # 3. Add Cachix caching to speed up repeated builds
      - name: Use Cachix
        uses: cachix/cachix-action@v10
        with:
          name: avro4s
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          push: true

      # 4. Run tests within the devShell defined in flake.nix
      - name: Run Scala 3 tests
        run: nix develop --command sbt test

      # 5. Build the project with Nix
      - name: Build with Nix
        run: nix build
